### ISSUE TITLE
Heroku question

### ISSUE THREAD

**Issue by Ouxhi** [loadletter/mangaupdates-urlfix#10]
I don't know anything about Heroku.com but I saw mention of an 18 hour limit for free "dynos" (https://blog.heroku.com/archives/2015/5/7/new-dyno-types-public-beta) and I believe when we submit a new url for a group, we are using heroku.com to do so (mufix.herokuapp.com/submit). I'm bringing this up because I'm aware some sites that use heroku were discussing having to move from heroku to somewhere else that's still free such as https://www.openshift.com/ . I don't know what either of those sites are for but just figured I'd ask if MUfix would be affected by the 18 hour limit.

**Comment by loadletter** [comment]
I don't think it should be an issue even with a larger number of submissions

**Comment by Ouxhi** [comment]
Ok, that's good. Thanks for the quick response,
