### ISSUE TITLE
Links not showing in FireFox 57

### ISSUE THREAD

**Issue by RichardW3D** [loadletter/mangaupdates-urlfix#14]
URLs no longer show in FireFox 57 when using Greasemonkey 4.

**Comment by loadletter** [comment]
I'll see what I can do

**Comment by loadletter** [comment]
Since GM 4 is a complete rewrite it leaves a lot to be desired, I'd suggest just switching to Violent Monkey (or TamperMonkey if you're willing to accept the EULA) and I've updated the readme to reflect this.
